import './globals.css'
import HeaderComponent from './header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <div className='flex flex-col h-screen'>
        <header className='sticky top-0 w-full'>
          <HeaderComponent />
        </header>
        <main className='flex-1 overflow-y-scroll'>
          <body>{children}</body>
        </main>
      </div>
    </html>
  )
}
