import './globals.css'
import HeaderComponent from './header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <div className='flex flex-col min-h-screen'>
        <header className='w-full fixed top-0'>
          <HeaderComponent />
        </header>
        <main>
          <body className='flex-1'>{children}</body>
        </main>
      </div>
    </html>
  )
}
